### ISSUE TITLE
スレタイ一覧に過去のスレが表示されるバグ

### ISSUE THREAD

**Issue by kazuki-nagashima** [edginer/eddist#2]
chmateにてジェスチェーでスレタイ一覧に戻ると過去のスレが表示されるバグが起きているようです
報告例を見てると皆共通して2024/10/18～19辺りのスレが表示されてるようなので、鯖移転が原因かと思われます
以下はこのバグが報告されたスレです

たまにエッヂ開くとこの画面にタイムワーブするようになっちゃったんやが
http://bbs.eddibb.cc/test/read.cgi/liveedge/1730301532/

【恐怖】エッヂかChMateに謎の不具合あるんやが・・・
http://bbs.eddibb.cc/test/read.cgi/liveedge/1730685931/

**Comment by edginer** [comment]
本件はchmate側のバグと想定されるためcloseさせていただきます
